### PR TITLE
Create 2016-07-20-announcing-dev-shop.md

### PR DESCRIPTION
**Pull request by hankyates**

### CODE REVIEW

**Comment by hankyates** [comment]
Don't merge yet. waiting on Ali to proofread.

**Comment by hankyates** [comment]
ok ... proofread. PTAL

**Comment by maxgaudin** [comment]
This is solid Hank. Do you think it might be good to expand on it a little bit further? You start to get inspiring and then it sort of just ends with hey we have a dev shop. Put a little bit more about how it makes you feel to work here and change lives. And expand on your role a little since you're also doing instruction, curriculum, working on internal tools, etc.

**Comment by hankyates** [comment]
👍

**Pull request closed without merging**
